### ISSUE TITLE
update needed for Inkscape version 1.0

### ISSUE THREAD

**Issue by brynnd** [fsmMLK/inkscapeMadeEasy#11]
Hello,
Thank you for providing this extension for Inkscape users!

This is just to let you know that most 3rd party Inkscape extensions, like this one, probably will not work with the upcoming new Inkscape version, the long-awaited version 1.0.

Here is the info you need to update this extension, so that it will work with 1.0 and future versions.  
https://wiki.inkscape.org/wiki/index.php?title=Updating_your_Extension_for_1.0

If you have further questions, you can contact Inkscape developers via [mailing lists](https://lists.inkscape.org/postorius/lists/?all-lists), [forum](https://inkscape.org/forums/extensions/), or the [chatroom](https://chat.inkscape.org/channel/inkscape_extensions).

If you have already updated it, please disregard this message.

All best,
brynn

**Comment by hohe** [comment]
Hello,

I tried to install and run this extension on Inkscape version 1.0 and it is not working. I assume that it is related to the necessary changes mentioned above.
Are you planning to work on the required changes in the near future?
If yes, I could possibly support you on this task.

Best regards,

Horst

**Comment by Jojo-1000** [comment]
I fixed all the obvious error messages and got it running with python 3 and inkscape 1.0 (together with circuit symbols). I broke backwards compatibility, because I have no experience with how to keep it compatible.

The changes are on my forks ([inkscapeMadeEasy](https://github.com/Jojo-1000/inkscapeMadeEasy/tree/port-inkscape-1.0), [inkscapeCircuitSymbols](https://github.com/Jojo-1000/inkscapeCircuitSymbols/tree/port-inkscape-1.0)) but I have not tested them thoroughly. Some things I just changed because it fixed the problems, I have no idea whether it is correct.

I would appreciate if someone takes a look at it to see whether I missed anything, especially for the other extensions or latex which I do not use.

**Comment by fsmMLK** [comment]
I am in the middle of a trip. As soon as I return I will check how to update all my plugins.

**Comment by fsmMLK** [comment]
inkscapeMadeEasy 1.0 is out! =D

At the moment inkscapeMadeEasy v1.0 is not compatible with all my plugins. I will update them to be compatible ASAP. There is a table in the main page of the repository with  the current status of the updates.
